# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Atelierbram Blog
subtitle: Documenting a Learning Curve
author: Bram de Haan <info@atelierbramdehaan.nl>
org: Atelier Bram de Haan
description: Blog-posts on Frontend Webdesign
keywords: Webdesign, Frontend, Design, 2D-Design, Documentation, Culture 
url: //localhost:8000
slug: //localhost:8000
slug_posts: //localhost:8000
url_license: //atelierbram.mit-license.org/
url_homepage: //atelierbram.github.io/blog/
url_codepen-blog: //codepen.io/atelierbram/blog
url_google-plus: //plus.google.com/+BramdeHaan/posts
url_atelier: //atelierbramdehaan.nl/
url_repository: //github.com/atelierbram/blog
url_repository-readme-link: //github.com/atelierbram/blog/blob/master/README.md
year_old: 2014
year_new: 2020
